### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by bheemreddy181-zz** [pact-foundation/pact-ruby-e2e-example#2]
Shouldn't these tasks come under consumer RAKE file >

https://github.com/pact-foundation/pact-ruby-e2e-example/blob/master/provider/Rakefile#L7-L18

**Comment by bethesque** [comment]
Does this answer your question? https://github.com/pact-foundation/pact-ruby-e2e-example/commit/c54dd9da813c58261b9a83e6249b1d62920fb72b

**Comment by bheemreddy181-zz** [comment]
Cool Perfect thanks 👍
