### ISSUE TITLE
[Question] : Provider mock on Consumer to use Https

### ISSUE THREAD

**Issue by bheemreddy181-zz** [pact-foundation/pact-ruby-e2e-example#3]
Is there a way I can say pact to use https rather than using http while creating the mock on consumer side for provider ?

**Comment by YOU54F** [comment]
Hey @bheemreddy181-zz - long time,

Sorry - answering an old question but there are docs in pact mock service regarding https use

https://github.com/pact-foundation/pact-mock_service?tab=readme-ov-file#with-ssl
